# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'SNSLogin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  
pod 'SDWebImage'

  # Pods for SNSLogin

  target 'SNSLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
